// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// }

export default function Layout({ children }) {
  return (
    <div>
      <p>This is a layout</p>
      {children}
    </div>
  )
}