import Layout from "@/components/layout"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function Home() {
  return (
    <Layout>
      <div>This is an example</div>
    </Layout>
  )
}
